######################################################################
# Automatically generated by qmake (3.0) Wed Nov 2 09:00:19 2016
######################################################################

TEMPLATE = app
TARGET = project
INCLUDEPATH += .\
            lodepng
CONFIG += c++11

# Input
HEADERS += algebra.h material.h polyroots.h scene.h shapes.h lodepng/lodepng.h \
    photon.h \
    misc.h \
    tests.h \
    camera.h \
    kdtree/kdtree.h \
    kdtree/kdtree.hxx \
    kdtree/timingstats.h \
    kdtree/mykdtree.h
SOURCES += algebra.cpp \
           material.cpp \
           polyroots.cpp \
           scene.cpp \
           lodepng/lodepng.cpp \
    photon.cpp \
    tests.cpp \
    camera.cpp \
    misc.cpp \
    kdtree/kdtest.cc \
    kdtree/timingstats.cc

unix:!macx: LIBS += -L$$PWD/../kdtree/ -lkdtree

INCLUDEPATH += $$PWD/../kdtree
DEPENDPATH += $$PWD/../kdtree
